class ShapeService < AttributeService
  SHAPES = {
    'Belicoso' => [
      'Belicoso',
      'BELICOSO',
      'BELICOSO,BOX PRESSED',
      'BELICOSO,TUBE',
      'Belicoso,',
      'Belicoso, Churchill, Cigarillos, Corona Extra, Double Corona, Gordo, Perfecto, Petite Corona, Robusto, Toro',
      'Belicoso, Churchill, Cigarillos, Corona, Double Corona, Gordo, Perfecto, Petite Corona, Robusto, Toro',
      'Belicoso, Churchill, Cigarillos, Corona, Double Perfecto, Gordo, Lancero/Panatela, Petite Corona, Pyramid, Robusto, Short Robusto, Toro, Torpedo',
      'Belicoso, Churchill, Cigarillos, Corona, Figurado, Gigante, Lancero/Panatela, Petite Corona, Presidente, Robusto, Toro',
      'Belicoso, Churchill, Cigarillos, Corona, Gordo, Petite Corona, Robusto, Toro',
      'Belicoso, Churchill, Cigarillos, Double Corona, Gordo, Lancero/Panatela, Lonsdale, Petite Corona, Presidente, Robusto, Toro',
      'Belicoso, Churchill, Cigarillos, Gordo, Lancero/Panatela, Petite Corona, Presidente, Robusto, Toro',
      'Belicoso, Churchill, Cigarillos, Gordo, Pyramid, Robusto, Toro',
      'Belicoso, Churchill, Cigarillos, Robusto, Toro',
      'Belicoso, Churchill, Corona, Double Corona, Gordo, Lancero/Panatela, Lonsdale, Petite Corona, Robusto',
      'Belicoso, Churchill, Corona, Double Corona, Gordo, Robusto, Toro',
      'Belicoso, Churchill, Corona, Double Corona, Robusto',
      'Belicoso, Churchill, Corona, Double Corona, Robusto, Toro',
      'Belicoso, Churchill, Corona, Double Robusto, Figurado, Gordo, Lancero/Panatela, Torpedo',
      'Belicoso, Churchill, Corona, Figurado, Lancero/Panatela, Lonsdale, Presidente, Robusto, Salomon, Toro, Torpedo',
      'Belicoso, Churchill, Corona, Gigante, Robusto, Toro',
      'Belicoso, Churchill, Corona, Gordo, Lancero/Panatela, Lonsdale, Robusto, Toro, Torpedo',
      'Belicoso, Churchill, Corona, Gordo, Lancero/Panatela, Presidente, Pyramid, Robusto, Toro, Torpedo',
      'Belicoso, Churchill, Corona, Gordo, Lonsdale, Perfecto, Presidente, Robusto, Toro, Torpedo',
      'Belicoso, Churchill, Corona, Gordo, Lonsdale, Robusto, Toro',
      'Belicoso, Churchill, Corona, Gordo, Perfecto, Presidente, Robusto, Salomon, Toro',
      'Belicoso, Churchill, Corona, Gordo, Petite Corona, Robusto, Toro',
      'Belicoso, Churchill, Corona, Gordo, Robusto',
      'Belicoso, Churchill, Corona, Gordo, Robusto, Toro',
      'Belicoso, Churchill, Corona, Lancero/Panatela, Robusto, Toro',
      'Belicoso, Churchill, Corona, Perfecto, Petite Corona, Pyramid, Robusto, Toro',
      'Belicoso, Churchill, Corona, Robusto, Toro',
      'Belicoso; Churchill; Corona; Toro',
      'Belicoso, Churchill, Double Robusto, Figurado, Perfecto, Robusto, Toro, Torpedo',
      'Belicoso; Churchill; Double Robusto; Presidente; Pyramid; Robusto; Toro',
      'Belicoso, Churchill, Figurado, Robusto, Toro',
      'Belicoso, Churchill, Gordo, Perfecto, Petite Corona, Robusto, Toro, Torpedo',
      'Belicoso, Churchill, Gordo, Pyramid, Robusto, Toro',
      'Belicoso, Churchill, Gordo, Robusto',
      'Belicoso, Churchill, Gordo, Robusto, Toro',
      'Belicoso; Churchill; Gordo; Rothschild; Toro',
      'Belicoso, Churchill, Gordo, Toro',
      'Belicoso, Churchill, Lancero/Panatela, Petite Corona, Robusto, Toro',
      'Belicoso, Churchill, Perfecto, Presidente, Robusto, Torpedo',
      'Belicoso, Churchill, Perfecto, Robusto, Toro',
      'Belicoso, Churchill, Robusto',
      'Belicoso, Churchill, Robusto Extra, Toro',
      'Belicoso, Churchill, Robusto, Toro',
      'Belicoso; Churchill; Robusto; Toro',
      'Belicoso, Cigarillos, Corona Extra, Double Corona, Lancero/Panatela, Perfecto, Petite Corona, Robusto, Toro',
      'Belicoso, Cigarillos, Corona Extra, Double Corona, Lancero/Panatela, Perfecto, Robusto, Toro',
      'Belicoso, Cigarillos, Corona, Double Corona, Gordo, Perfecto, Robusto, Toro',
      'Belicoso, Cigarillos, Corona, Gordo, Lonsdale, Robusto, Toro',
      'Belicoso, Cigarillos, Robusto, Toro',
      'Belicoso, Corona',
      'Belicoso, Corona Extra, Gordo, Lancero/Panatela, Toro',
      'Belicoso, Corona Extra, Toro',
      'Belicoso; Corona Gorda; Robusto',
      'Belicoso, Corona Gorda, Robusto, Toro',
      'Belicoso, Corona, Double Corona',
      'Belicoso; Corona; Double Corona; Gigante; Robusto',
      'Belicoso, Corona, Double Robusto, Presidente, Robusto',
      'Belicoso; Corona; Double Toro; Petite Corona; Robusto; Toro',
      'Belicoso, Corona, Gordo, Robusto, Toro',
      'Belicoso; Corona; Gordo; Toro',
      'Belicoso, Corona, Lancero/Panatela, Robusto, Toro',
      'Belicoso, Corona, Robusto, Toro',
      'Belicoso, Corona, Rothschild, Toro',
      'Belicoso, Double Perfecto, Gordo, Robusto',
      'Belicoso, Double Robusto, Gordo, Short Robusto',
      'Belicoso, Gordo, Lancero/Panatela, Robusto, Toro',
      'Belicoso, Gordo, Lancero, Robusto Extra, Toro',
      'Belicoso, Gordo, Perfecto, Presidente, Robusto',
      'Belicoso, Gordo, Perfecto, Robusto',
      'Belicoso; Gordo; Petite Corona; Robusto; Toro',
      'Belicoso, Gordo, Presidente, Robusto',
      'Belicoso, Gordo, Robusto',
      'Belicoso; Gordo; Robusto',
      'Belicoso, Gordo, Robusto, Toro',
      'Belicoso; Gordo; Robusto; Toro',
      'Belicoso, Gordo, Toro',
      'Belicoso, Lonsdale',
      'Belicoso; Panatela; Perfecto; Petite Corona; Robusto; Short Robusto',
      'Belicoso; Perfecto; Petite Corona; Robusto',
      'Belicoso; Perfecto; Petite Corona; Robusto Extra; Short Robusto',
      'Belicoso, Perfecto, Toro',
      'Belicoso, Petite Corona',
      'Belicoso, Petite Corona, Robusto, Toro',
      'Belicoso; Presidente; Robusto; Toro',
      'Belicoso, Robusto',
      'Belicoso, Robusto, Robusto Extra, Toro',
      'Belicoso, Robusto, Toro',
      'Belicoso; Robusto; Toro',
      'Belicoso, Short Robusto, Toro',
      'Belicoso, Toro',
      'Belicoso; Toro',
      'belicoso'
    ],
    'Box Pressed' => [
      'Box-pressed',
      'BOX PRESSED',
      'BOX PRESSED,CHURCHILL',
      'BOX PRESSED,FIGURADO',
      'BOX PRESSED,GORDO',
      'Box Pressed Parejo',
      'BOX PRESSED,ROBUSTO',
      'BOX PRESSED,TORO',
      'Box Pressed Torpedo',
      'BOX PRESSED,TORPEDO',
      'Box Pressed'
    ],
    'Churchill' => [
      'Churchill',
      'CHURCHILL',
      'CHURCHILL GORDO',
      'CHURCHILL,PERFECTO',
      'CHURCHILL,TUBE',
      'CHURCHILL,TUBO',
      'Churchill; Cigarillos',
      'Churchill, Cigarillos, Corona, Double Corona, Lonsdale, Presidente, Robusto, Rothschild, Toro, Torpedo',
      'Churchill, Cigarillos, Corona, Double Corona, Lonsdale, Robusto, Torpedo',
      'Churchill, Cigarillos, Corona, Double Corona, Perfecto, Robusto, Toro, Torpedo',
      'Churchill, Cigarillos, Corona, Double Corona, Robusto, Toro, Torpedo',
      'Churchill, Cigarillos, Corona, Figurado, Gigante, Lancero/Panatela, Robusto',
      'Churchill, Cigarillos, Corona, Gigante, Robusto, Toro',
      'Churchill, Cigarillos, Corona, Gordo, Lancero/Panatela, Lonsdale, Presidente, Robusto, Toro, Torpedo',
      'Churchill, Cigarillos, Corona, Gordo, Robusto, Toro',
      'Churchill, Cigarillos, Corona, Lancero/Panatela, Lonsdale, Petite Corona, Presidente, Rothschild, Toro',
      'Churchill, Cigarillos, Corona, Lonsdale, Petite Corona, Robusto, Toro',
      'Churchill, Cigarillos, Corona, Lonsdale, Pyramid, Robusto, Toro',
      'Churchill, Cigarillos, Corona, Presidente, Robusto',
      'Churchill, Cigarillos, Corona, Robusto, Toro',
      'Churchill, Cigarillos, Gigante, Gordo, Robusto, Toro',
      'Churchill, Cigarillos, Gigante, Robusto, Robusto Extra, Toro',
      'Churchill, Cigarillos, Gigante, Robusto, Toro',
      'Churchill, Cigarillos, Gordo, Perfecto, Petite Corona, Robusto, Toro, Torpedo',
      'Churchill, Cigarillos, Gordo, Robusto, Toro',
      'Churchill, Cigarillos, Gordo, Robusto, Toro, Torpedo',
      'Churchill, Cigarillos, Robusto',
      'Churchill, Cigarillos, Robusto, Toro',
      'Churchill, Corona',
      'Churchill, Corona Extra, Figurado, Gordo, Petite Corona, Robusto, Toro, Torpedo',
      'Churchill, Corona Extra, Robusto Extra',
      'Churchill, Corona Extra, Robusto, Toro, Torpedo',
      'Churchill, Corona Extra, Robusto, Torpedo',
      'Churchill, Corona Gigante, Gordo, Perfecto, Petite Corona, Robusto, Toro, Torpedo',
      'Churchill, Corona Gorda, Gordo, Robusto, Toro',
      'Churchill; Corona Gorda; Gordo; Robusto; Toro',
      'Churchill, Corona Gorda, Gordo, Robusto, Toro, Torpedo',
      'Churchill, Corona Gorda, Robusto',
      'Churchill; Corona Gorda; Toro; Torpedo',
      'Churchill, Corona, Corona Gorda, Gordo, Robusto, Toro',
      'Churchill, Corona, Corona Gorda, Robusto, Robusto Extra, Short Robusto, Toro, Torpedo',
      'Churchill, Corona, Double Corona, Gordo, Lancero/Panatela, Robusto, Torpedo',
      'Churchill, Corona, Double Corona, Gordo, Presidente, Pyramid, Robusto, Toro',
      'Churchill, Corona, Double Corona, Gordo, Robusto, Short Robusto, Toro',
      'Churchill, Corona, Double Corona, Lancero/Panatela, Torpedo',
      'Churchill, Corona, Double Corona, Lonsdale, Presidente, Rothschild, Toro',
      'Churchill; Corona; Gigante; Robusto; Toro',
      'Churchill, Corona, Gigante, Robusto, Toro, Torpedo',
      'Churchill, Corona, Gordo, Gordo Extra, Robusto',
      'Churchill, Corona, Gordo, Lancero/Panatela, Petite Corona, Presidente, Robusto, Toro, Torpedo',
      'Churchill, Corona, Gordo, Lancero/Panatela, Petite Corona, Robusto',
      'Churchill, Corona, Gordo, Lancero/Panatela, Petite Corona, Robusto, Torpedo',
      'Churchill, Corona, Gordo, Lancero/Panatela, Presidente, Toro, Torpedo',
      'Churchill; Corona; Gordo; Lonsdale; Presidente; Robusto; Toro',
      'Churchill, Corona, Gordo, Perfecto, Robusto, Toro, Torpedo',
      'Churchill; Corona; Gordo; Petite Corona; Robusto; Short Robusto; Toro; Torpedo',
      'Churchill, Corona, Gordo, Presidente, Robusto, Toro, Torpedo',
      'Churchill, Corona, Gordo, Pyramid, Robusto, Toro',
      'Churchill; Corona; Gordo; Pyramid; Robusto; Toro',
      'Churchill, Corona, Gordo, Robusto',
      'Churchill, Corona, Gordo, Robusto, Toro',
      'Churchill; Corona; Gordo; Robusto; Toro',
      'Churchill, Corona, Gordo, Robusto, Toro, Torpedo',
      'Churchill; Corona; Gordo; Robusto; Toro; Torpedo',
      'Churchill; Corona; Lancero/Panatela',
      'Churchill, Corona, Lancero/Panatela, Lonsdale, Presidente, Robusto, Toro',
      'Churchill; Corona; Lancero/Panatela; Lonsdale; Robusto; Toro',
      'Churchill, Corona, Lancero/Panatela, Robusto, Toro',
      'Churchill, Corona, Perfecto, Robusto, Toro, Torpedo',
      'Churchill; Corona; Petite Corona; Pyramid; Robusto; Toro',
      'Churchill; Corona; Presidente; Robusto; Toro',
      'Churchill, Corona, Robusto',
      'Churchill; Corona; Robusto',
      'Churchill, Corona, Robusto Extra',
      'Churchill, Corona, Robusto, Short Robusto',
      'Churchill, Corona, Robusto, Toro',
      'Churchill; Corona; Robusto; Toro',
      'Churchill, Corona, Robusto, Toro, Torpedo',
      'Churchill, Corona, Robusto, Torpedo',
      'Churchill, Corona, Toro',
      'Churchill; Corona; Toro; Torpedo',
      'Churchill, Double Corona',
      'Churchill, Double Corona, Gordo, Perfecto, Petite Corona, Robusto, Toro',
      'Churchill; Double Corona; Gordo; Presidente; Robusto; Toro; Torpedo',
      'Churchill, Double Corona, Petite Corona, Presidente, Robusto, Toro',
      'Churchill, Double Robusto, Gordo, Short Robusto, Toro, Torpedo',
      'Churchill, Double Robusto, Pyramid',
      'Churchill, Figurado, Gordo, Petite Corona, Robusto, Torpedo',
      'Churchill, Figurado, Gordo, Robusto',
      'Churchill, Figurado, Gordo, Robusto, Toro',
      'Churchill, Figurado, Gordo, Robusto, Toro, Torpedo',
      'Churchill, Figurado, Robusto, Toro',
      'Churchill, Figurado, Robusto, Torpedo',
      'Churchill; Gigante; Robusto',
      'Churchill, Gigante, Robusto, Rothschild',
      'Churchill, Gigante, Robusto, Toro',
      'Churchill; Gigante; Robusto; Toro',
      'Churchill, Gordo',
      'Churchill; Gordo',
      'Churchill, Gordo, Lancero/Panatela, Pyramid, Robusto',
      'Churchill, Gordo, Lonsdale, Petite Corona, Robusto, Toro, Torpedo',
      'Churchill, Gordo, Lonsdale, Presidente, Robusto, Toro, Torpedo',
      'Churchill, Gordo, Lonsdale, Toro, Torpedo',
      'Churchill, Gordo, Perfecto',
      'Churchill, Gordo, Perfecto, Petite Corona, Robusto, Toro, Torpedo',
      'Churchill, Gordo, Perfecto, Robusto, Toro, Torpedo',
      'Churchill, Gordo, Petite Corona, Robusto, Toro, Torpedo',
      'Churchill; Gordo; Presidente; Robusto; Toro; Torpedo',
      'Churchill, Gordo, Pyramid, Robusto, Toro',
      'Churchill, Gordo, Robusto',
      'Churchill; Gordo; Robusto',
      'Churchill, Gordo, Robusto, Salomon, Toro',
      'Churchill; Gordo; Robusto; Salomon; Toro',
      'Churchill, Gordo, Robusto, Salomon, Toro, Torpedo',
      'Churchill, Gordo, Robusto, Short Robusto',
      'Churchill, Gordo, Robusto, Toro',
      'Churchill; Gordo; Robusto; Toro',
      'Churchill, Gordo, Robusto, Toro, Torpedo',
      'Churchill, Gordo, Robusto, Torpedo',
      'Churchill; Gordo; Robusto; Torpedo',
      'Churchill, Gordo, Toro',
      'Churchill; Gordo; Toro',
      'Churchill, Lancero/Panatela, Robusto',
      'Churchill; Lonsdale; Presidente; Robusto',
      'Churchill; Lonsdale; Presidente; Robusto; Toro; Torpedo',
      'Churchill, Lonsdale, Robusto, Salomon, Toro, Torpedo',
      'Churchill, Lonsdale, Robusto, Toro',
      'Churchill, Perfecto, Petite Corona, Robusto, Toro, Torpedo',
      'Churchill, Perfecto, Robusto, Toro, Torpedo',
      'Churchill, Perfecto, Toro',
      'Churchill; Petite Corona',
      'Churchill, Petite Corona, Robusto, Toro',
      'Churchill; Petite Corona; Robusto; Toro; Torpedo',
      'Churchill; Presidente',
      'Churchill, Presidente, Robusto, Toro, Torpedo',
      'Churchill, Pyramid, Robusto, Toro',
      'Churchill, Pyramid, Short Robusto, Toro',
      'Churchill, Robusto',
      'Churchill; Robusto',
      'Churchill, Robusto, Rothschild, Salomon, Toro',
      'Churchill, Robusto, Rothschild, Toro',
      'Churchill; Robusto; Short Robusto',
      'Churchill, Robusto, Toro',
      'Churchill; Robusto; Toro',
      'Churchill, Robusto, Toro, Torpedo',
      'Churchill; Robusto; Toro; Torpedo',
      'Churchill, Robusto, Torpedo',
      'Churchill, Toro',
      'Churchill; Toro',
      'Churchill, Toro, Torpedo',
      'Churchill; Toro; Torpedo',
      'Churchill, Torpedo',
      'Churchill; Torpedo',
      'Shape Machine Made Cigars',
      'churchill',
      'Churchill (7.0"x48)',
      'Churchill (7.0"x49)',
      'Churchill (7.0"x50)',
      'churchill extra',
      'churchill tubos'
    ],
    'Cigarillos' => [
      'Cigarillo',
      'Cigarillos',
      'Cigarillos; Corona',
      'Cigarillos; Corona; Corona Extra; Presidente; Robusto; Rothschild; Toro',
      'Cigarillos, Corona, Corona Extra, Toro',
      'Cigarillos, Corona, Corona Gorda',
      'Cigarillos, Corona, Double Corona, Figurado, Perfecto, Robusto, Toro, Torpedo',
      'Cigarillos, Corona, Double Corona, Lonsdale, Perfecto, Presidente, Robusto, Rothschild, Toro',
      'Cigarillos, Corona, Double Robusto, Robusto, Toro',
      'Cigarillos, Corona, Gordo, Lancero/Panatela, Perfecto, Robusto, Toro',
      'Cigarillos, Corona, Gordo, Perfecto, Robusto, Short Robusto',
      'Cigarillos, Corona, Gordo, Petite Corona, Pyramid, Robusto, Toro, Torpedo',
      'Cigarillos, Corona, Gordo, Petite Corona, Robusto, Toro',
      'Cigarillos, Corona, Gordo, Petite Corona, Short Robusto',
      'Cigarillos, Corona, Gordo, Robusto',
      'Cigarillos, Corona, Lancero/Panatela, Petite Corona, Robusto, Toro',
      'Cigarillos, Corona, Perfecto, Petite Corona',
      'Cigarillos; Corona; Petite Corona',
      'Cigarillos, Corona, Petite Corona, Robusto, Torpedo',
      'Cigarillos, Corona, Petite Corona, Toro',
      'Cigarillos, Corona, Robusto',
      'Cigarillos, Corona, Robusto, Toro',
      'Cigarillos, Gigante, Gordo, Pyramid, Robusto, Rothschild, Toro',
      'Cigarillos, Gigante, Toro',
      'Cigarillos, Gordo, Robusto, Toro',
      'Cigarillos, Lonsdale, Robusto, Toro, Torpedo',
      'Cigarillos, Petite Corona',
      'Cigarillos; Petite Corona; Toro; Torpedo',
      'Cigarillos; Pyramid; Robusto; Toro',
      'Cigarillos, Robusto, Toro',
      'Cigarillos, Robusto, Torpedo',
      'Cigarillo',
      'cigarillos'
    ],
    'Corona' => [
      'Corona',
      'CORONA',
      'Corona Especial',
      'Corona Extra',
      'CORONA EXTRA',
      'Corona Extra, Double Corona, Gordo, Robusto, Torpedo',
      'Corona Extra, Figurado, Gordo, Robusto, Short Robusto',
      'Corona Extra, Gordo, Lancero/Panatela, Petite Corona, Robusto, Toro',
      'Corona Extra, Gordo, Petite Corona, Robusto, Toro',
      'Corona Extra, Gordo, Robusto, Toro',
      'Corona Extra, Gordo, Robusto, Torpedo',
      'Corona Extra, Gran Rothschild, Short Robusto, Toro, Torpedo',
      'Corona Extra, Lonsdale, Pyramid, Robusto, Toro',
      'Corona Extra; Perfecto; Robusto; Robusto Extra; Toro',
      'Corona Extra; Petite Corona; Robusto',
      'Corona Gigante, Robusto, Torpedo',
      'Corona Gorda',
      'CORONA GORDA',
      'Corona Gorda, Double Toro, Robusto Extra, Toro',
      'Corona Gorda; Double Toro; Robusto; Short Robusto; Toro',
      'Corona Gorda; Double Toro; Robusto; Toro',
      'Corona Gorda; Gordo; Robusto Extra; Toro',
      'Corona Gorda; Gordo; Robusto; Toro',
      'Corona Gorda, Gordo, Toro',
      'Corona Gorda; Gordo; Toro',
      'Corona Gorda, Lancero/Panatela, Robusto Extra, Short Robusto, Toro',
      'Corona Gorda; Lancero/Panatela; Robusto; Toro',
      'Corona Gorda, Lonsdale, Robusto, Toro',
      'Corona Gorda; Petite Corona; Toro',
      'Corona Gorda, Robusto',
      'Corona Gorda; Robusto',
      'Corona Gorda, Robusto, Toro',
      'Corona Gorda; Robusto; Toro',
      'Corona Gorda, Robusto, Toro, Torpedo',
      'Corona Gorda; Toro',
      'Corona Gordo',
      'Corona Grande',
      'CORONA GRANDE',
      'Corona Grande, Robusto Extra, Rothschild',
      'CORONA LARGA',
      'Corona Minor',
      'CORONA,TUBE',
      'CORONA,TUBO',
      'Corona Viva',
      'Corona, Corona Especial, Lancero/Panatela, Pyramid, Robusto',
      'Corona; Corona Extra; Perfecto; Robusto; Robusto Extra; Toro',
      'Corona, Corona Extra, Robusto, Toro',
      'Corona, Double Corona, Figurado, Robusto, Toro, Torpedo',
      'Corona, Double Corona, Gordo, Robusto, Toro, Torpedo',
      'Corona, Double Corona, Lancero/Panatela, Robusto, Toro, Torpedo',
      'Corona, Double Corona, Lancero, Robusto, Toro',
      'Corona; Double Corona; Lonsdale; Robusto; Toro',
      'Corona; Double Corona; Presidente; Pyramid; Robusto; Toro',
      'Corona, Double Corona, Robusto, Toro',
      'Corona, Double Robusto, Robusto, Rothschild',
      'Corona; Double Toro; Robusto; Toro',
      'Corona, Figurado, Gordo, Robusto, Rothschild, Toro',
      'Corona, Figurado, Gordo, Wedge',
      'Corona, Figurado, Presidente, Robusto, Toro',
      'Corona; Gigante; Robusto',
      'Corona, Gigante, Toro, Torpedo',
      'Corona, Gordo, Gordo Extra, Robusto, Toro',
      'Corona, Gordo, Lonsdale, Robusto, Toro, Torpedo',
      'Corona; Gordo; Petite Corona; Robusto; Robusto Extra; Rothschild; Toro',
      'Corona, Gordo, Petite Corona, Robusto, Toro',
      'Corona, Gordo, Robusto',
      'Corona; Gordo; Robusto',
      'Corona, Gordo, Robusto, Rothschild, Toro, Torpedo',
      'Corona, Gordo, Robusto, Toro',
      'Corona; Gordo; Robusto; Toro',
      'Corona, Gordo, Robusto, Toro, Torpedo',
      'Corona; Gordo; Robusto; Torpedo',
      'Corona; Gordo; Toro',
      'Corona, Gordo, Toro, Torpedo',
      'Corona, Gordo, Torpedo',
      'Corona, Lancero/Panatela',
      'Corona; Lancero/Panatela; Rothschild; Toro',
      'Corona, Lancero/Panatela, Short Robusto, Toro',
      'Corona, Lancero, Robusto, Short Robusto, Toro, Torpedo',
      'Corona, Lonsdale, Pyramid, Robusto, Toro',
      'Corona, Lonsdale, Rothschild, Short Robusto',
      'Corona, Perfecto, Robusto',
      'Corona; Petite Corona; Robusto',
      'Corona, Petite Corona, Robusto, Toro',
      'Corona, Petite Corona, Robusto, Toro, Torpedo',
      'Corona, Pyramid, Robusto, Toro',
      'Corona; Pyramid; Robusto; Toro',
      'Corona, Robusto',
      'Corona; Robusto',
      'Corona, Robusto, Robusto Extra, Toro',
      'Corona, Robusto, Rothschild, Toro',
      'Corona, Robusto, Salomon, Toro',
      'Corona, Robusto, Toro',
      'Corona; Robusto; Toro',
      'Corona, Short Robusto',
      'Corona; Toro',
      'Corona, Lonsdale, Perfecto',
      'corona',
      'Corona (5.3"x45)',
      'corona extra',
      'Corona Extra',
      'corona gorda',
      'Corona Gorda',
      'Corona Grande; Rothschild',
      'corona larga',
      'corona tubos'
    ],
    'Double Corona' => [
      'corona doble',
      'Double Corona',
      'DOUBLE CORONA',
      'Double Corona, Gordo, Robusto',
      'Double Corona; Gordo; Robusto',
      'Double Corona, Gordo, Robusto, Toro',
      'Double Corona, Gordo, Robusto, Toro, Torpedo',
      'Double Corona, Gordo, Rothschild, Toro',
      'Double Corona; Gordo; Toro',
      'Double Corona; Lancero/Panatela; Robusto',
      'Double Corona, Lonsdale, Robusto, Toro',
      'Double Corona; Presidente; Pyramid; Robusto; Toro; Torpedo',
      'Double Corona; Presidente; Toro',
      'Double Corona, Robusto',
      'Double Corona, Robusto, Short Robusto, Toro',
      'Double Corona, Robusto, Toro',
      'Double Corona; Robusto; Toro',
      'Double Corona, Robusto, Toro, Torpedo',
      'Double Corona, Toro',
      'double corona',
      ''
    ],
    'Double Gordo' => [
      'Double Gordo',
      'DOUBLE GORDO'
    ],
    'Double Perfecto' => [
      'Double Perfecto',
      'Double Perfecto, Gordo, Robusto',
      'Double Perfecto; Gordo; Robusto; Toro',
      'Double Perfecto, Perfecto',
      'Double Perfecto; Perfecto',
      'Double Perfecto, Robusto, Toro',
      'Double Perfecto, Toro',
      'double perfecto'
    ],
    'Double Robusto' => [
      'Double Robusto',
      'DOUBLE ROBUSTO',
      'Double Robusto, Gordo, Perfecto, Robusto',
      'Double Robusto, Gordo, Robusto, Toro',
      'Double Robusto; Gordo; Robusto; Toro',
      'Double Robusto, Gordo, Toro',
      'Double Robusto, Gordo, Toro, Torpedo',
      'Double Robusto, Perfecto',
      'Double Robusto, Petite Corona, Toro, Torpedo',
      'Double Robusto, Robusto, Toro',
      'Double Robusto; Toro',
      'double robusto',
      'double robusto tubos'
    ],
    'Double Toro' => [
      'Double Toro',
      'DOUBLE TORO,GORDO',
      'Double Toro, Gordo, Lonsdale, Robusto Extra',
      'Double Toro; Toro',
      'double toro'
    ],
    'Figurado' => [
      'Figurado',
      'FIGURADO',
      'Figurado, Gordo, Perfecto, Rothschild, Toro',
      'Figurado, Gordo, Presidente, Robusto, Toro',
      'Figurado, Gordo, Robusto',
      'Figurado, Robusto',
      'figurado'
    ],
    'Gigante' => [
      'Gigante',
      'GIGANTE',
      'Gigante; Gordo',
      'Gigante, Gordo, Robusto, Toro',
      'Gigante, Gordo, Short Robusto',
      'Gigante; Presidente; Robusto',
      'Gigante, Robusto, Rothschild, Toro',
      'Gigante, Robusto, Rothschild, Toro, Torpedo',
      'Gigante, Robusto, Toro',
      'Gigante, Rothschild, Toro',
      'Gigante; Toro',
      'Gigaante',
      'gigante'
    ],
    'Gordito' => [
      'Gordito',
      'GORDITO',
      'gordito'
    ],
    'Gordo' => [
      'Gordo',
      'GORDO',
      'Gordo Extra',
      'GORDO,PERFECTO',
      'GORDO,TUBE',
      'Gordo,',
      'Gordo, Lancero/Panatela',
      'Gordo, Lancero/Panatela, Petite Corona, Robusto, Toro',
      'Gordo, Lancero/Panatela, Robusto',
      'Gordo; Lancero/Panatela; Robusto',
      'Gordo, Lancero/Panatela, Robusto, Toro',
      'Gordo; Lancero/Panatela; Robusto; Toro',
      'Gordo, Lancero/Panatela, Robusto, Toro, Torpedo',
      'Gordo, Lancero/Panatela, Robusto, Torpedo',
      'Gordo, Lancero, Lancero/Panatela, Robusto, Toro',
      'Gordo, Lancero, Robusto, Toro',
      'Gordo, Lonsdale, Robusto, Toro',
      'Gordo; Lonsdale; Robusto; Toro',
      'Gordo, Perfecto',
      'Gordo, Perfecto, Robusto',
      'Gordo; Perfecto; Robusto',
      'Gordo, Perfecto, Robusto, Toro',
      'Gordo; Perfecto; Robusto; Toro',
      'Gordo, Perfecto, Robusto, Toro, Torpedo',
      'Gordo, Perfecto, Short Robusto, Torpedo',
      'Gordo, Petite Corona, Robusto',
      'Gordo; Petite Corona; Robusto Extra; Torpedo',
      'Gordo, Petite Corona, Robusto, Toro',
      'Gordo, Petite Corona, Robusto, Toro, Torpedo',
      'Gordo, Petite Corona, Rothschild, Toro',
      'Gordo; Petite Corona; Rothschild; Toro',
      'Gordo, Petite Corona, Torpedo',
      'Gordo, Presidente, Robusto, Toro, Torpedo',
      'Gordo, Pyramid, Robusto',
      'Gordo, Pyramid, Robusto, Toro',
      'Gordo, Robusto',
      'Gordo, Robusto Extra',
      'Gordo, Robusto Extra, Toro',
      'Gordo, Robusto, Robusto Extra, Toro, Torpedo',
      'Gordo; Robusto; Robusto Extra; Toro; Torpedo',
      'Gordo, Robusto, Salomon, Toro',
      'Gordo; Robusto; Salomon; Toro',
      'Gordo, Robusto, Short Robusto, Toro',
      'Gordo; Robusto; Short Robusto; Toro',
      'Gordo, Robusto, Toro',
      'Gordo; Robusto; Toro',
      'Gordo, Robusto, Toro, Torpedo',
      'Gordo; Robusto; Toro; Torpedo',
      'Gordo; Robusto; Toro; Wedge',
      'Gordo, Robusto, Torpedo',
      'Gordo; Robusto; Wedge',
      'Gordo, Short Robusto',
      'Gordo, Short Robusto, Torpedo',
      'Gordo, Toro',
      'Gordo; Toro',
      'Gordo, Toro, Torpedo',
      'Gordo, Torpedo',
      'godro',
      'gordo',
      'gordo tubos'
    ],
    'Grand Corona' => [
      'Gran Corona',
      'GRAN CORONA',
      'Grand Corona'
    ],
    'Grand Robusto' => [
      'Grand Robusto',
      'Grand Rothschild',
      'GRAN ROBUSTO',
      'GRAN ROBUSTO,TUBE',
      'Gran Rothschild'
    ],
    'Gran Toro' => [
      'Gran Toro',
      'GRAN TORO',
      'gran toro'
    ],
    'Lancero' => [
      'Lancero',
      'LANCERO',
      'Lancero/Panatela',
      'Lancero/Pantella',
      'Lancero; Lancero/Panatela',
      'Lancero, Lancero/Panatela, Lonsdale, Pyramid, Robusto, Toro',
      'Lancero/Panatela, Robusto, Toro',
      'Lancero/Panatela, Short Robusto',
      'Lancero/Panatela, Toro',
      'lancero',
      'Lancero / Panatela'
    ],
    'Cigarillo' => [
      'Cigarillo',
      'Cigarillos',
      'Cigarillos,',
      'Cigarillos, Corona',
      'Cigarillos, Corona, Lancero/Panatela, Presidente',
      'Cigarillos, Lancero/Panatela',
      'Cigarillos, Lonsdale',
      'Cigarilos'
    ],
    'Petit Corona' => [
      'Petit Corona',
      'Petite Corona'
    ],
    'Small Cigar' => [
      'Small Cigar',
      'Small Panatela'
    ],
    'Tip Cigarillo' => [
      'Tip Cigarillo',
      'Tip Cigarillos'
    ],
    'Varies' => [
      'Varies',
      'Various'
    ],
    'Lonsdale' => [
      'Lonsdale',
      'LONSDALE',
      'Lonsdale Grande',
      'Lonsdale; Perfecto; Robusto',
      'Lonsdale; Presidente; Robusto; Toro; Torpedo',
      'Lonsdale, Pyramid, Robusto, Toro',
      'Lonsdale, Robusto, Rothschild, Torpedo',
      'Lonsdale, Robusto, Short Robusto, Toro',
      'Lonsdale, Robusto, Toro',
      'Lonsdale; Robusto; Toro; Torpedo',
      'LONSDALE,TUBE',
      'LONSDALE,TUBO',
      'lonsdale'
    ],
    'Panatela' => [
      'Panatela',
      'PANATELA',
      'Panatela, Robusto, Toro',
      'Panatela; Robusto; Toro',
      'panatela'
    ],
    'Parejo' => [
      'Parejo',
      'Parejo/pyramid',
      'Parejo/rat Tail'
    ],
    'Perfecto' => [
      'Perfecto',
      'PERFECTO',
      'Perfecto, Petite Corona',
      'Perfecto, Robusto',
      'Perfecto; Rothschild',
      'Perfecto; Toro; Torpedo',
      'perfecto',
      'perfecto tubos'
    ],
    'Petit' => [
      'Petit',
      'Petit Corona',
      'PETITE',
      'PETITE BELICOSO',
      'PETITE CORONA',
      'Petite Corona, Pyramid, Robusto, Short Robusto, Toro',
      'Petite Corona; Robusto',
      'Petite Corona, Robusto Extra',
      'Petite Corona; Robusto; Robusto Extra; Toro',
      'Petite Corona, Torpedo',
      'Petite Gordo',
      'Petite Robusto',
      'PETITE ROBUSTO',
      'Petit Corona',
      'petite corona',
      'Petite Corona',
      'petite robusto gordo',
      'petit robusto'
    ],
    'Presidente' => [
      'Presidente',
      'PRESIDENTE',
      'Presidente; Robusto',
      'Presidente, Robusto, Toro',
      'Presidente, Robusto, Toro, Torpedo',
      'Presidente, Robusto, Torpedo',
      'Presidente, Toro',
      'presidente'
    ],
    'Pyramid' => [
      'Pyramid',
      'Pyramid,',
      'PYRAMID',
      'Pyramide',
      'Pyramid, Robusto, Toro',
      'Pyramid; Robusto; Toro',
      'Pyramid; Rothschild',
      'piramide',
      'Piramide',
      'pyramid'
    ],
    'Robusto' => [
      'Robusto',
      'ROBUSTO',
      'Robusto Extra',
      'Robusto Extra; Short Robusto',
      'Robusto Extra, Toro',
      'Robusto Extra; Toro',
      'Robusto Gordo',
      'ROBUSTO GORDO',
      'Robusto Grande',
      'ROBUSTO GRANDE',
      'ROBUSTO GRANDE,TUBO',
      'Robusto; Robusto Extra',
      'Robusto, Robusto Extra, Short Robusto, Toro',
      'Robusto, Robusto Extra, Toro',
      'Robusto, Robusto Extra, Toro, Torpedo',
      'Robusto, Rothschild, Toro',
      'Robusto, Salomon',
      'Robusto, Salomon, Toro, Torpedo',
      'Robusto, Short Robusto, Toro',
      'Robusto, Toro',
      'Robusto; Toro',
      'Robusto, Toro, Torpedo',
      'Robusto; Toro; Torpedo',
      'Robusto; Toro; Wedge',
      'Robusto, Torpedo',
      'Robusto; Torpedo',
      'Robusto; Torpedo; Wedge',
      'ROBUSTO,TUBE',
      'ROBUSTO,TUBO',
      'robusto',
      'Robusto (5.5" x 52)',
      'robusto extra',
      'Robusto Extra',
      'robusto fino',
      'robusto gordo',
      'robusto larga',
      'robusto tubos'
    ],
    'Rothchild' => [
      'Rothchild',
      'Rothchilde',
      'Rothschild',
      'ROTHSCHILD',
      'ROTHSCHILD,TUBE',
      'rothschild',
      'rothschilde'
    ],
    'Salomon' => [
      'Salomon',
      'SALOMON',
      'salamone',
      'salomone'
    ],
    'Short Gordo' => [
      'SHORT GORDO',
      'SHORT GORDO,TUBO'
    ],
    'Short Magnum' => [
      'Short Magnum',
      'SHORT MAGNUM'
    ],
    'Short Panatela' => [
      'Short Panatela',
      'SHORT PANATELA'
    ],
    'Short Robusto' => [
      'Short Robusto',
      'SHORT ROBUSTO'
    ],
    'Short Torpedo' => [
      'Short Torpedo',
      'SHORT TORPEDO'
    ],
    'Toro' => [
      'toro',
      'Toro',
      'TORO',
      'Toro Gordo',
      'TORO GORDO',
      'Toro Grande',
      'Toro, Torpedo',
      'Toro; Torpedo',
      'TORO,TUBE',
      'TORO,TUBO',
      'toro',
      'Toro (6.0"x54)',
      'toro extra',
      'toro gordo',
      'toro grande',
      'toro tubos'
    ],
    'Torpedo' => [
      'Torpedo',
      'TORPEDO',
      'torpedo',
      'torpedo gordo'
    ],
    'Tube' => [
      'TUBE',
      'TUBO'
    ]
  }

  def self.merge!
    SHAPES.each do |shape, names|
      names.each do |name|
        Product.where('shape_fltr ILIKE ?', name).update_all shape_fltr: shape if shape != name
      end
    end

    %w(shape shapes).each do |key|
      Product.where("specifications ? '#{ key }'").each do |product|
        product.specifications[key] = shape product.specifications[key]
        product.save if product.changed?
      end
    end

    Product.pluck(:shape_fltr).uniq.compact.each do |shape_fltr|
      Product
          .where(shape_fltr: shape_fltr)
          .update_all(shape_fltr: shape(shape_fltr))
    end
  end

  def self.shape(_shape)
    self.select_name _shape, SHAPES
  end
end
